name = "worker"
main = "src/worker.ts"
compatibility_date = "2023-06-28"
node_compat = true

[vars]
# The necessary secrets are:
# - SUPABASE_URL
# - SUPABASE_KEY
# - LIVEBLOCKS_SECRET



[durable_objects]
bindings = [
  { name = "LiveWorker", class_name = "LiveWorker" },
]


[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["LiveWorker"] 